name: ✨ Feature Request
description: Suggest a new feature
title: "✨ Feature Request: "
labels: [✨ feature]
body:
  - type: textarea
    attributes:
      label: Feature Description
      description: Provide a detailed description of the feature you are suggesting. Explain why it would be useful and how it should work.
      placeholder: "Describe the feature..."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Use Case
      description: Describe the use case for this feature. Explain how you or others would use it and what problem it would solve.
      placeholder: "Describe the use case..."
    validations:
      required: true
  - type: input
    attributes:
      label: Additional Context
      description: Provide any additional context or information that might be relevant to the feature request.
      placeholder: "Add any other context or screenshots here..."
    validations:
      required: false
