import {
  MLKIT_FEATURE_KEYS,
  type MLKitFeature,
} from 'react-native-vision-camera-mlkit';

export enum PLUGIN_ID {
  TEXT_RECOGNITION,
  FACE_DETECTION,
  FACE_MESH_DETECTION,
  POSE_DETECTION,
  SEGMENTATION_SELFIE,
  SEGMENTATION_SUBJECT,
  DOCUMENT_SCANNER,
  BARCODE_SCANNING,
  IMAGE_LABELING,
  OBJECT_DETECTION,
  DIGITAL_INK_RECOGNITION,
}

export const pluginIdToName: Record<PLUGIN_ID, MLKitFeature> = {
  [PLUGIN_ID.TEXT_RECOGNITION]: MLKIT_FEATURE_KEYS.TEXT_RECOGNITION,
  [PLUGIN_ID.FACE_DETECTION]: MLKIT_FEATURE_KEYS.FACE_DETECTION,
  [PLUGIN_ID.FACE_MESH_DETECTION]: MLKIT_FEATURE_KEYS.FACE_MESH_DETECTION,
  [PLUGIN_ID.POSE_DETECTION]: MLKIT_FEATURE_KEYS.POSE_DETECTION,
  [PLUGIN_ID.SEGMENTATION_SELFIE]: MLKIT_FEATURE_KEYS.SELFIE_SEGMENTATION,
  [PLUGIN_ID.SEGMENTATION_SUBJECT]: MLKIT_FEATURE_KEYS.SUBJECT_SEGMENTATION,
  [PLUGIN_ID.DOCUMENT_SCANNER]: MLKIT_FEATURE_KEYS.DOCUMENT_SCANNER,
  [PLUGIN_ID.BARCODE_SCANNING]: MLKIT_FEATURE_KEYS.BARCODE_SCANNING,
  [PLUGIN_ID.IMAGE_LABELING]: MLKIT_FEATURE_KEYS.IMAGE_LABELING,
  [PLUGIN_ID.OBJECT_DETECTION]: MLKIT_FEATURE_KEYS.OBJECT_DETECTION,
  [PLUGIN_ID.DIGITAL_INK_RECOGNITION]:
    MLKIT_FEATURE_KEYS.DIGITAL_INK_RECOGNITION,
};

export const isPluginId = (v: number): v is PLUGIN_ID => v in pluginIdToName;
